[project]
name = 'cli'

[[jobs]]
name = 'build'
run = '''
cargo build --release --workspace
'''
artifacts = ['target/x86_64-unknown-linux-musl/release/brr']
# [jobs.env]
# name = { secret = 'name', version = 11 }

[containers.musl]
image = "clux/muslrust:1.55.0-stable"
