on:
  push:
    branches:
      - "main"
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download brr
        env:
          TAG: 0.0.14
        run: |
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr

      - name: brr build
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
        run: |
          brr run build musl
