on:
  push:
    tags:
      - "*"
name: Release
jobs:
  build and release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            brr_cmd: brr run build musl
          - target: x86_64-apple-darwin
            brr_cmd: brr run macos-build darwin-builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download brr
        env:
          TAG: 0.0.21
        run: |
          env
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr -V

      - name: brr build
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
        run: |
          ${{ matrix.brr_cmd }}

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # file: target/release/brr
          file: target/${{ matrix.target }}/release/brr
          asset_name: brr-$tag-${{ matrix.target }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
