on:
  push:
    tags:
      - "*"
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download brr
        env:
          TAG: 0.0.10
        run: |
          env
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr

      - name: brr build
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
        run: |
          brr run brr

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/brr
          asset_name: brr-$tag-x86_64-unknown-linux-musl
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
