on:
  push:
    tags:
      - "*"
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      - name: Download brr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURL="curl -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          https://api.github.com/repos/buildrecall/brr/releases"; \
          ASSET_ID=$(eval "$CURL/tags/0.0.1" | jq .assets[0].id); \
          eval "$CURL/assets/$ASSET_ID -LJOH 'Accept: application/octet-stream'"
          sudo mv brr-0.0.1-x86_64-unknown-linux-gnu /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          ./brr

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release
      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/release/brr
      #     asset_name: brr-$tag-x86_64-unknown-linux-gnu
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: ""
